# Dependency Review configuration
# For the Docusaurus website migration, we allow all permissive licenses
# commonly found in the Node.js/npm ecosystem

allow-licenses:
  - '0BSD'
  - 'Apache-2.0'
  - 'BlueOak-1.0.0'
  - 'BSD-2-Clause'
  - 'BSD-2-Clause-Views'
  - 'BSD-3-Clause'
  - 'CC0-1.0'
  - 'CC-BY-4.0'
  - 'ISC'
  - 'MIT'
  - 'MIT-0'
  - 'Python-2.0'
  - 'Unlicense'

# Deny only restrictive licenses, allow everything else
fail-on-severity: 'critical'
