os: Visual Studio 2017
version: 5.0.0-beta-{build}
configuration: Release
cache:
  - packages
before_build:
  - dotnet restore
clone_depth: 1
build:
  project: JustSaying.sln
  parallel: true
  verbosity: minimal
pull_requests:
  do_not_increment_build_number: true
test_script:
  - ps: ni -ItemType Directory -path ".\output\nunit"
  - ps: $wc = New-Object 'System.Net.WebClient'
  - dotnet run --project .\JustSaying.AwsTools.UnitTests\JustSaying.AwsTools.UnitTests.csproj --result=.\output\nunit\JustSaying.AwsTools.UnitTests.TestResults.xml
  - dotnet run --project .\JustSaying.Messaging.UnitTests\JustSaying.Messaging.UnitTests.csproj --result=.\output\nunit\JustSaying.Messaging.UnitTests.TestResults.xml
  - dotnet run --project .\JustSaying.UnitTests\JustSaying.UnitTests.csproj --result=.\output\nunit\JustSaying.UnitTests.TestResults.xml
  - ps: gci .\output\nunit\ -filter *.xml | % { $webClient.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", $_.FullName) }
after_build:
- dotnet pack .\JustSaying\JustSaying.csproj -o ../output --no-build
- dotnet pack .\JustSaying.AwsTools\JustSaying.AwsTools.csproj -o ../output --no-build
- dotnet pack .\JustSaying.Messaging\JustSaying.Messaging.csproj -o ../output --no-build
- dotnet pack .\JustSaying.Models\JustSaying.Models.csproj -o ../output --no-build
artifacts:
- path: 'output\*.nupkg'
notifications:
- provider: HipChat
  room: 'Eng :: Open Source'
  auth_token:
    secure: eJWABMRPoyfEF9iLzFaTcUEqTc7/64v0FtS1qQe4yhs=
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
- provider: Webhook
  url: https://webhooks.gitter.im/e/1d5903ab716f417802d0
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
