image: Visual Studio 2019
version: 7.0.{build}

branches:
  only:
    - master

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%

build_script:
  - ps: .\Build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\coverage.cobertura.xml"

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: '**\$(APPVEYOR_PROJECT_NAME)*.*nupkg'
    name: NuGet

pull_requests:
  do_not_increment_build_number: true

skip_tags: false
test: off

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/1d5903ab716f417802d0
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
