version: 5.0.{build}-beta
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: |
    $projectFiles = @(
      "JustSaying\project.json",
      "JustSaying.AwsTools\project.json",
      "JustSaying.AwsTools.IntegrationTests\project.json",
      "JustSaying.AwsTools.UnitTests\project.json",
      "JustSaying.IntegrationTests\project.json",
      "JustSaying.Messaging\project.json",
      "JustSaying.Messaging.UnitTests\project.json",
      "JustSaying.Models\project.json",
      "JustSaying.TestingFramework\project.json",
      "JustSaying.Tools\project.json",
      "JustSaying.UnitTests\project.json"
    )
    foreach ($projectFile  in $projectFiles) {
      $project =  Get-Content $projectFile -Raw | ConvertFrom-Json
      $project.version = $env:APPVEYOR_BUILD_VERSION
      ConvertTo-Json $project -Depth 100 | Out-File -Encoding UTF8 $projectFile
    }
- ps: dotnet restore
- ps: dotnet build JustSaying/project.json
test_script:
  - dotnet test .\JustSaying.AwsTools.UnitTests\project.json --result=myresults.xml;format=AppVeyor
  - dotnet test .\JustSaying.Messaging.UnitTests\project.json --result=myresults.xml;format=AppVeyor
  - dotnet test .\JustSaying.UnitTests\project.json --result=myresults.xml;format=AppVeyor
after_build:
- dotnet pack "JustSaying" -o artifacts --no-build
- dotnet pack "JustSaying.AwsTools" -o artifacts --no-build
- dotnet pack "JustSaying.Messaging" -o artifacts --no-build
- dotnet pack "JustSaying.Models" -o artifacts --no-build
artifacts:
- path: artifacts\**\*.*
notifications:
- provider: HipChat
  room: 'Eng :: Open Source'
  auth_token:
    secure: eJWABMRPoyfEF9iLzFaTcUEqTc7/64v0FtS1qQe4yhs=
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
- provider: Webhook
  url: https://webhooks.gitter.im/e/1d5903ab716f417802d0
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
deploy:
- provider: NuGet
  api_key:
    secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
